name: Update Exercises

on:
  schedule:
    - cron: '59 23 * * 0" # Runs at 23:59, only on Sunday
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run update script
        run: npm run update-exercises
